[project]
name = "game-genie-mcp"
version = "0.1.0"
description = "MCP server that exposes Unity functions to the LLM"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.4.1",
]
